@startuml 画面遷移図
left to right direction
[*] -> 利用者ログイン画面
[*] --> 管理者ログイン画面

利用者ログイン画面 -> アカウント登録 
管理者ログイン画面 --> ユーザー管理機能

ユーザー管理機能 -> パスワードリセット画面
ユーザー管理機能 --> ログアウト

利用者ログイン画面 -> エラー画面 :ログイン失敗
エラー画面 -> 利用者ログイン画面 
利用者ログイン画面 --> カレンダー :ログイン成功

state カレンダー {
    カレンダー画面 --> 目標金額設定画面
    カレンダー画面 -> 日報作成
    カレンダー画面 --> 消費した金額登録
    目標金額設定画面 --> 収入登録
    日報作成 --> カテゴリー追加
    日報作成 --> カテゴリー編集
    日報作成 --> カテゴリー削除
    日報作成 --> カテゴリー検索
    カテゴリー検索 -> 検索したカテゴリー金額表示
    消費した金額登録 --> レシートの画像認識
    日報作成 -> 消費した合計金額
    カレンダー画面 --> 合計金額表示
    合計金額表示 --> 差額計算

}
カレンダー -> 目標までの残額表示
@enduml