@startuml
left to right direction
actor 利用者 as user
actor 管理者 as admin

rectangle 利用者機能 {
  usecase ログイン as login
  usecase 目標金額登録 as set_goal
  usecase 収入登録 as add_income
  usecase 消費した金額登録 as add_expense
  usecase レシートの画像認識 as image_recognition
  usecase カテゴリー編集 as manage_category
  usecase 計算機能 as calculations
  usecase タイトル編集 as edit_title
  usecase 日報作成機能 as create_report
  
  
  user --> login
  user --> set_goal
  user --> add_income
  user --> add_expense
  user --> image_recognition
  user --> manage_category
  user --> calculations
  user --> edit_title
  user --> create_report
}

  rectangle 管理者機能 {
  usecase 管理者ログイン as admin_login
  usecase ログアウト as account_logout

  admin --> admin_login
  admin --> account_logout
  

}
@enduml