@startuml
left to right direction
actor 利用者 as user
actor 管理者 as admin

rectangle 利用者機能 {
  usecase ログイン as login
  usecase カレンダー表示 as show_calendar
  usecase 日報作成 as create_report
  usecase カテゴリー選択 as select_category_input
  usecase 収入入力 as sup_input
  usecase 合計金額更新 as update_total
  usecase 目標金額登録 as set_goal
  usecase 消費した金額登録 as add_expense
  usecase レシートの画像認識 as image_recognition
  usecase カテゴリー編集 as manage_category
  usecase 計算機能 as calculations
  usecase タイトル編集 as edit_title
  usecase 日報追加機能 as create_report
  
  
  user --> login
  login --> show_calendar
  show_calendar --> set_goal
  show_calendar --> add_expense
  show_calendar --> image_recognition
  show_calendar --> manage_category
  show_calendar --> calculations
  show_calendar --> edit_title
  show_calendar --> create_report :<<include>>
  create_report <-- select_category_input :<<include>>
  create_report <-- sup_input :<<include>>
  create_report -right-> update_total
  
}



rectangle 管理者機能 {
  usecase 管理者ログイン as admin_login
  usecase ユーザー管理 as user_kan
  usecase ログアウト as account_logout

  admin --> admin_login
  admin_login --> user_kan
  admin_login --> account_logout
}


@enduml