@startuml
state スマートフォンの画面 {
    state 医院診察予約{
        state メニュー
        state 今の順番
    }
    state 予約と確認画面{
        state お名前
        state 電話番号
        state 登録
        state 取消
    }
    state あなたの順番{
        state 登録者番号
    }
    state 今の順番 {
        state 診察中の患者の番号
    }

    [*] --> 医院診察予約
    医院診察予約 --> メニュー
    予約と確認画面 --> 今の順番
    メニュー --> 予約と確認画面 : 予約する
    予約と確認画面 --> お名前 : 登録情報入力
    予約と確認画面 --> 電話番号 : 登録情報入力
    お名前 --> 登録
    電話番号 --> 登録
    お名前 --> 取消
    電話番号 --> 取消
    登録 --> あなたの順番
    取消 --> メニュー
}

@enduml