@startuml
object 客
object ボタン
object 料金装置
object ベンダー装置

客 -> ボタン: ドリンク選択
ボタン -> 料金装置: 支払い要求
料金装置 --> ボタン: 支払い金額
ボタン -> 客: 支払い金額表示
客 -> ボタン: 支払い完了
ボタン -> ベンダー装置: ドリンク提供要求
ベンダー装置 --> ボタン: ドリンク提供
ボタン -> 客: ドリンク受取通知

@enduml