@startuml
[*] --> 電源スイッチOFF

state 電源スイッチOFF {
    電源スイッチOFF --> 電源スイッチON :電源スイッチをONにする
}

state 電源スイッチON {
    state 右旋回 {
        右旋回 --> 左旋回 :光センサーがラインを外れる
        右旋回 --> 電源スイッチOFF :　電源スイッチをOFFにする
    }
}

電源スイッチOFF --> [*]