@startuml 演習2-1
left to right direction
actor 申請者 as user #DDDDDD;line:black;line.bold;
actor 交通費精算システム as system #DDDDDD;line:black;line.bold;
actor 承認者 as syou #DDDDDD;line:black;line.bold;
actor 経理担当者 as keiri #DDDDDD;line:black;line.bold;
rectangle 出張申請システム {
 usecase 出張申請を登録する as T
 usecase 出張申請を申請する as P
 usecase 出張申請を承認する as S
 usecase 出張申請を却下する as K
 usecase 出張申請を差し戻す as R
 usecase 出張申請を確認する as C
}
user -->T
user -->P
syou -->S
syou -->K
syou -->R
syou -->C
keiri -->C
T <--system